version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my-postgres-db
    env_file:
      - ./.env.postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jonatanav255 -d myworkdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    env_file:
      - ./.env.backend
    build:
      context: ${BACKEND_CONTEXT:-./backend}
      dockerfile: Dockerfile
    container_name: my-backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ${FRONTEND_CONTEXT:-./frontend}
      dockerfile: Dockerfile
    container_name: my-frontend
    ports:
      - "3000:80"  # Host port 3000 mapped to container port 80 (default for Nginx)
    depends_on:
      - backend

volumes:
  pgdata:
